name: stuff

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: xt0rted/markdownlint-problem-matcher@v1
      - uses: DavidAnson/markdownlint-cli2-action@v7
        with:
          globs: "**/*.md"

  size-label:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    permissions:
      pull-requests: write
    steps:
      - name: size-label
        uses: "pascalgn/size-label-action@v0.4.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          INPUT_SIZES: >
            {
              "0": "XS",
              "30": "S",
              "100": "M",
              "250": "L",
              "500": "XL",
              "1000": "XXL"
            }
  clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v3
        with:
          path: |
            ./llvm
          key: llvm-16
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "16.0"
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}
      - name: Symlink libclang.so
        run: |
          sudo ln -s libclang.so /usr/lib/x86_64-linux-gnu/libclang-16.so
          ls -la
          pwd
          echo "The env version ${{ env.LLVM_PATH }}"
          echo "The bash version $LLVM_PATH"
          "[ -e /usr/lib/x86_64-linux-gnu/libclang-16.so ]"
        working-directory: ${{ env.LLVM_PATH }}
